### ISSUE TITLE
multi line function code

### ISSUE THREAD

**Issue by darlenya** [JoshuaWise/expression-sandbox#4]
Hi,

I would like to compile code like this:

const myFunc = '
    const res = {};
    res.email = 'my.name@gmail.com';
    res.email2 = 'faker.internet.email()';
    return JSON.stringify(res);
'
const code = compiler(myFunc);
const result = code({ JSON });
console.log(result);

But this does not work because of the hardcoded 'return' statement. Is there a way to compile code like this?

Or would you accept a pull request with an additional compile function?

**Comment by JoshuaWise** [comment]
the hardcoded `return` statement exists for security reasons. The only way to compile multiple statements is to wrap your code in an [IIFE](https://en.wikipedia.org/wiki/Immediately-invoked_function_expression), like so:

```js
const myFunc = `(function () {
  const res = {};
  res.email = 'my.name@gmail.com';
  res.email2 = 'faker.internet.email()';
  return JSON.stringify(res);
}())`
```

**Comment by darlenya** [comment]
Great this works. Thanks a lot.
